name: IPTV M3U Extraction

on:
  # Run automatically every 10 minutes
  schedule:
    - cron: '*/40 * * * *'  # Run every 40 minutes (cron syntax: minute hour day month day-of-week)

  # Manual trigger
  workflow_dispatch:

jobs:
  extract-m3u:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GPD5 }}  # Use the secret token here

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from requirements.txt (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # Step 4: Clear the specialiptvs directory
      - name: Clear specialiptvs directory
        run: |
          if [ -d specialiptvs ]; then
            rm -rf specialiptvs/*
          else
            mkdir -p specialiptvs
          fi

      # Step 5: Ensure the fixmac.txt file exists
      - name: Check for fixmac.txt
        run: |
          if [ ! -f fixmac.txt ]; then
            echo "fixmac.txt not found!"
            exit 1
          fi

      # Step 6: Run the IPTV extraction script
      - name: Run IPTV extraction script
        run: |
          python hotrun.py

      # Step 7: Commit and push changes (if there are any)
      - name: Commit and push changes
        env:
          GPD5: ${{ secrets.GPD5 }}  # Use the secret token here
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            git add specialiptvs/
            git commit -m "Auto-extracted and updated M3U files at $(date)"
            # Pull changes from remote first to avoid conflicts
            git pull origin main --rebase
            # Push changes
            git push origin main
          else
            echo "No changes to commit."
          fi
